apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      securityContext:
        fsGroup: 65533 # rocketchat group ID
        runAsUser: 65533 # rocketchat user ID
        runAsGroup: 65533 # rocketchat group ID

      containers:
        - name: rocketchat
          image: registry.rocket.chat/rocketchat/rocket.chat:7.10.0
          ports:
            - containerPort: 3000
            - containerPort: 9458

          securityContext:
            allowPrivilegeEscalation: false

          env:
            - name: PORT
              value: "3000"
            - name: DEPLOY_METHOD
              value: docker
            - name: OVERWRITE_SETTING_Prometheus_Enabled
              value: "true"
            - name: OVERWRITE_SETTING_Prometheus_Port
              value: "9458"
            - name: REG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rocketchat-config
                  key: regToken
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rocketchat-config
                  key: dbUsername
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rocketchat-config
                  key: dbPassword
            - name: MONGO_URL
              value: >-
                mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@rocketchat-db-production-cluster-v1-rs0.rocketchat.svc.cluster.local/rocketchat?replicaSet=rs0&ssl=false
